## Employee Career Survey Analysis

In [1]:
import pandas as pd  
import numpy as np 
import plotly.express as px  
import plotly.graph_objects as go

In [2]:
df = pd.read_csv('Data.csv')

In [3]:
df.head()

,Your Current Country.,Your Current Zip Code / Pin Code,Your Gender,Which of the below factors influence the most about your career aspirations ?,Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.,How likely is that you will work for one employer for 3 years or more ?,Would you work for a company whose mission is not clearly defined and publicly posted.,How likely would you work for a company whose mission is misaligned with their public actions or even their product ?,How likely would you work for a company whose mission is not bringing social impact ?,What is the most preferred working environment for you.,Which of the below Employers would you work with.,Which type of learning environment that you are most likely to work in ?,Which of the below careers looks close to your Aspirational job ?,What type of Manager would you work without looking into your watch ?,Which of the following setup you would like to work ?
0,India,273005,Male,People who have changed the world for better,"Yes, I will earn and do that","This will be hard to do, but if it is the righ...",No,Will NOT work for them,4,Fully Remote with No option to visit offices,Employer who rewards learning and enables that...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...","Work alone, Work with 2 to 3 people in my team..."
1,India,851129,Male,People who have changed the world for better,"No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,1,Fully Remote with Options to travel as and whe...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Instructor or Exp...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...",Work with 5 to 6 people in my team
2,India,123106,Female,Social Media like LinkedIn,"Yes, I will earn and do that",Will work for 3 years or more,Yes,Will work for them,7,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Trial and error b...",Manage and drive End-to-End Projects or Produc...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."
3,India,834003,Male,"People from my circle, but not family members","No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,6,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Manag...","Manager who explains what is expected, sets a ...",Work with 2 to 3 people in my team
4,India,301019,Female,Influencers who had successful careers,"No, But if someone could bare the cost I will",Will work for 3 years or more,No,Will NOT work for them,5,Fully Remote with Options to travel as and whe...,Employer who appreciates learning and enables ...,"Self Paced Learning Portals, Learning by obser...",Teaching in any of the institutes/online or Of...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."

In [4]:
df.shape

(235, 15)

In [5]:
df.columns

Index(['Your Current Country.', 'Your Current Zip Code / Pin Code',
       'Your Gender',
       'Which of the below factors influence the most about your career aspirations ?',
       'Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.',
       'How likely is that you will work for one employer for 3 years or more ?',
       'Would you work for a company whose mission is not clearly defined and publicly posted.',
       'How likely would you work for a company whose mission is misaligned with their public actions or even their product ?',
       'How likely would you work for a company whose mission is not bringing social impact ?',
       'What is the most preferred working environment for you.',
       'Which of the below Employers would you work with.',
       'Which type of learning environment that you are most likely to work in ?',
       'Which of the below careers looks close to your Aspirational job ?',
       'What type of Manager would you work without looking into your watch ?',
       'Which of the following setup you would like to work ?'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 15 columns):
 #   Column                                                                                                                    Non-Null Count  Dtype
---  ------                                                                                                                    --------------  -----
 0   Your Current Country.                                                                                                     235 non-null    object
 1   Your Current Zip Code / Pin Code                                                                                          235 non-null    int64
 2   Your Gender                                                                                                               235 non-null    object
 3   Which of the below factors influence the most about your career aspirations ?                                             235 non-null    object
 4   Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.  235 non-null    object
 5   How likely is that you will work for one employer for 3 years or more ?                                                   235 non-null    object
 6   Would you work for a company whose mission is not clearly defined and publicly posted.                                    235 non-null    object
 7   How likely would you work for a company whose mission is misaligned with their public actions or even their product ?     235 non-null    object
 8   How likely would you work for a company whose mission is not bringing social impact ?                                     235 non-null    int64
 9   What is the most preferred working environment for you.                                                                   235 non-null    object
 10  Which of the below Employers would you work with.                                                                         235 non-null    object
 11  Which type of learning environment that you are most likely to work in ?                                                  235 non-null    object
 12  Which of the below careers looks close to your Aspirational job ?                                                         235 non-null    object
 13  What type of Manager would you work without looking into your watch ?                                                     235 non-null    object
 14  Which of the following setup you would like to work ?                                                                     235 non-null    object
dtypes: int64(2), object(13)
memory usage: 27.7+ KB

In [7]:
df.isna().sum()

Your Current Country.                                                                                                       0
Your Current Zip Code / Pin Code                                                                                            0
Your Gender                                                                                                                 0
Which of the below factors influence the most about your career aspirations ?                                               0
Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.    0
How likely is that you will work for one employer for 3 years or more ?                                                     0
Would you work for a company whose mission is not clearly defined and publicly posted.                                      0
How likely would you work for a company whose mission is misaligned with their public actions or even their product ?       0
How likely would you work for a company whose mission is not bringing social impact ?                                       0
What is the most preferred working environment for you.                                                                     0
Which of the below Employers would you work with.                                                                           0
Which type of learning environment that you are most likely to work in ?                                                    0
Which of the below careers looks close to your Aspirational job ?                                                           0
What type of Manager would you work without looking into your watch ?                                                       0
Which of the following setup you would like to work ?                                                                       0
dtype: int64

In [8]:
Country = df["Your Current Country."].value_counts()
Country

India                       231
Germany                       2
United Arab Emirates          1
United States of America      1
Name: Your Current Country., dtype: int64

In [9]:
Country = df["Your Current Country."].value_counts()
label = Country.index
counts = Country.values
colors =['red','lightgreen']
fig=go.Figure(data=[go.Pie(labels=label,values=counts)])
fig.update_layout(title_text="Current Country")
fig.update_traces(hoverinfo='label+value',textinfo='percent',textfont_size=30,
                  marker=dict(colors=colors,line=dict(color='black',width=3)))
fig.show()

## Factors influencing career objective

In [26]:


q1 = df["Which of the below factors influence the most about your career aspirations ?"].value_counts()
label = q1.index
counts = q1.values
colors = ['gold', 'lightblue']

fig = go.Figure(data=[go.Pie(labels=label, values=counts)])

fig.update_layout(
    title_text="Factors Influencing Career Aspiration",
    width=700,  
    height=500   
)

fig.update_traces(
    hoverinfo='label+value',
    textinfo='percent',
    textfont_size=20,
    marker=dict(colors=colors, line=dict(color='black', width=3))
)

fig.show()

In [32]:
df['Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.'].value_counts()

Yes, I will earn and do that                                    110
No I would not be pursuing Higher Education outside of India     65
No, But if someone could bare the cost I will                    60
Name: Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it., dtype: int64

In [30]:


q2 = df["Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it."].value_counts()
label = q2.index
counts = q2.values
colors = ['gold', 'lightblue']

fig = go.Figure(data=[go.Pie(labels=label, values=counts)])

fig.update_layout(
    title_text="Factors Influencing Career Aspiration",
    width=700,  
    height=500   
)

fig.update_traces(
    hoverinfo='label+value',
    textinfo='percent',
    textfont_size=20,
    marker=dict(colors=colors, line=dict(color='black', width=3))
)

fig.show()

In [35]:
df['How likely is that you will work for one employer for 3 years or more ?'].value_counts()

This will be hard to do, but if it is the right company I would try    139
Will work for 3 years or more                                           79
No way, 3 years with one employer is crazy                              17
Name: How likely is that you will work for one employer for 3 years or more ?, dtype: int64

In [36]:


q3 = df["How likely is that you will work for one employer for 3 years or more ?"].value_counts()
label = q3.index
counts = q3.values
colors = ['gold', 'lightblue']

fig = go.Figure(data=[go.Pie(labels=label, values=counts)])

fig.update_layout(
    title_text="Factors Influencing Career Aspiration",
    width=700,  
    height=500   
)

fig.update_traces(
    hoverinfo='label+value',
    textinfo='percent',
    textfont_size=20,
    marker=dict(colors=colors, line=dict(color='black', width=3))
)

fig.show()

In [37]:
df.head()

,Your Current Country.,Your Current Zip Code / Pin Code,Your Gender,Which of the below factors influence the most about your career aspirations ?,Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.,How likely is that you will work for one employer for 3 years or more ?,Would you work for a company whose mission is not clearly defined and publicly posted.,How likely would you work for a company whose mission is misaligned with their public actions or even their product ?,How likely would you work for a company whose mission is not bringing social impact ?,What is the most preferred working environment for you.,Which of the below Employers would you work with.,Which type of learning environment that you are most likely to work in ?,Which of the below careers looks close to your Aspirational job ?,What type of Manager would you work without looking into your watch ?,Which of the following setup you would like to work ?
0,India,273005,Male,People who have changed the world for better,"Yes, I will earn and do that","This will be hard to do, but if it is the righ...",No,Will NOT work for them,4,Fully Remote with No option to visit offices,Employer who rewards learning and enables that...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...","Work alone, Work with 2 to 3 people in my team..."
1,India,851129,Male,People who have changed the world for better,"No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,1,Fully Remote with Options to travel as and whe...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Instructor or Exp...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...",Work with 5 to 6 people in my team
2,India,123106,Female,Social Media like LinkedIn,"Yes, I will earn and do that",Will work for 3 years or more,Yes,Will work for them,7,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Trial and error b...",Manage and drive End-to-End Projects or Produc...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."
3,India,834003,Male,"People from my circle, but not family members","No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,6,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Manag...","Manager who explains what is expected, sets a ...",Work with 2 to 3 people in my team
4,India,301019,Female,Influencers who had successful careers,"No, But if someone could bare the cost I will",Will work for 3 years or more,No,Will NOT work for them,5,Fully Remote with Options to travel as and whe...,Employer who appreciates learning and enables ...,"Self Paced Learning Portals, Learning by obser...",Teaching in any of the institutes/online or Of...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."

In [39]:
df['What is the most preferred working environment for you.'].value_counts()

Fully Remote with Options to travel as and when needed                 60
Hybrid Working Environment with less than 15 days a month at office    57
Every Day Office Environment                                           50
Hybrid Working Environment with less than 10 days a month at office    31
Hybrid Working Environment with less than 3 days a month at office     26
Fully Remote with No option to visit offices                           11
Name: What is the most preferred working environment for you., dtype: int64

In [41]:


q4 = df["What is the most preferred working environment for you."].value_counts()
label = q4.index
counts = q4.values
# colors = ['gold', 'lightblue']

fig = go.Figure(data=[go.Pie(labels=label, values=counts)])

fig.update_layout(
    title_text="Factors Influencing Career Aspiration",
    width=800,  
    height=500   
)

fig.update_traces(
    hoverinfo='label+value',
    textinfo='percent',
    textfont_size=20,
    marker=dict(colors=colors, line=dict(color='black', width=3))
)

fig.show()